# Places from "Qatar address.pdf" (English stored value, Arabic checkout label).
QATAR_AREAS = [
    ("West Bay", "الخليج الغربي"),
    ("Wadi Lusail", "وادي لوسيل"),
    ("Wadi Al Sail", "وادي السيل"),
    ("Wadi Al Banat", "وادي البنات"),
    ("Umm Salal Mohammed", "أم صلال محمد"),
    ("Umm Salal Ali", "أم صلال علي"),
    ("Umm Obayeria", "أم عبيرية"),
    ("Umm Lekhba", "أم لخبا"),
    ("Umm Ghuwailina", "أم غويلينا"),
    ("Umm Garn", "أم قرن"),
    ("Umm Birka", "أم بركة"),
    ("Umm Al Seneem", "أم السنيم"),
    ("Umm Al Amad", "أم العمد"),
    ("Um Bab", "ام باب"),
    ("TinBak", "تينباك"),
    ("Simaisma", "سميسمة"),
    ("Shagra", "شقراء"),
    ("Sawda Natheel", "سودة نثيل"),
    ("Rawdat Al Khail", "روضة الخيل"),
    ("Rawdat Al Hamam", "روضة الحمام"),
    ("Rass Laffan", "راس لفان"),
    ("Ras Abu Fontas", "راس ابو فنطاس"),
    ("Ras Abu Abboud", "راس ابو عبود"),
    ("Qatar University", "جامعة قطر"),
    ("Pearl Qatar", "لؤلؤة قطر"),
    ("Onaiza", "عنيزة"),
    ("Old Salata", "سلاطة القديمة"),
    ("Old Al Rayyan", "الريان القديم"),
    ("Old Al Hitmi", "الهتمي القديم"),
    ("Old Al Ghanim", "الغانم القديم"),
    ("Old Airport", "المطار القديم"),
    ("New Salata", "السلطة الجديدة"),
    ("New Al Rayyan", "الريان الجديد"),
    ("New Al Khulaifat", "الخليفات الجديدة"),
    ("New Al Hitmi", "الهتمي جديد"),
    ("New Al Ghanim", "الغانم الجديد"),
    ("Najma", "نجمة"),
    ("Musheireb", "مشيرب"),
    ("Muraikh", "مريخ"),
    ("Muaither South", "معيذر الجنوبية"),
    ("Muaither North", "معيذر الشمالية"),
    ("Muaither", "معيذر"),
    ("Mesaimeer", "مسيمير"),
    ("Mesaieed Industrial Area", "منطقة مسيعيد الصناعية"),
    ("Mesaieed", "مسيعيد"),
    ("Mehairja", "ميهيرجا"),
    ("Madinat Khalifa South", "مدينة خليفة الجنوبية"),
    ("Madinat Khalifa North", "مدينة خليفة الشمالية"),
    ("Lusail", "لوسيل"),
    ("Luaib", "لويب"),
    ("Lejmail", "لجمايل"),
    ("Legtaifiya - West Bay Lagoon", "لقطيفية - الخليج الغربي لاجون"),
    ("Land Mark Area", "منطقة لاند مارك"),
    ("Jeryan Najaima", "جريان نجيمة"),
    ("Jabal Thuaileb", "جبل ثويلب"),
    ("Izghawa", "إزغاوا"),
    ("Industrial Area", "منطقة صناعية"),
    ("Hazm Al Markhiya", "حزم المرخية"),
    ("Hamad Medical City", "مدينة حمد الطبية"),
    ("Hamad", "حامد"),
    ("New Souq", "السوق الجديد"),
    ("Fereej Kulaib", "فريج كليب"),
    ("Fereej Bin Dirham", "فريج بن درهم"),
    ("Fereej Al Ameer", "فريج الأمير"),
    ("Fereej Al Ali", "فريج العلي"),
    ("Fereej Abdul Aziz", "فريج عبد العزيز"),
    ("Education City - Qatar Foundation", "المدينة التعليمية - مؤسسة قطر"),
    ("Dukhan", "دخان"),
    ("Doha Port", "ميناء الدوحة"),
    ("Dahl Al Hamam", "دحل الحمام"),
    ("Bu Nakhla", "بو نخله"),
    ("Bin Omran", "بن عمران"),
    ("Bin Mahmoud", "بن محمود"),
    ("Barwa Village", "قرية بروة"),
    ("Barwa City", "مدينة بروة"),
    ("Baraht Al Jufairi", "بارحت الجفيري"),
    ("Bani Hajar", "بني حجر"),
    ("Baaya", "بايا"),
    ("Al Wukair", "الوكير"),
    ("Al Wakrah", "الوكرة"),
    ("Al Wajba", "الوجبة"),
    ("Al Waab", "الوعب"),
    ("Al Utouriya", "العتورية"),
    ("Al Thumama", "الثمامة"),
    ("Al Thakhira", "الذخيرة"),
    ("Al Souq", "السوق"),
    ("Al Soudan", "السودان"),
    ("Al Sheehaniya", "الشيحانية"),
    ("Al Sakhama", "الصخامة"),
    ("Al Sailiya", "السيلية"),
    ("Al Sadd", "السد"),
    ("Al Rumaila", "الرميلة"),
    ("Al Rufaa", "الرفاع"),
    ("Al Qassar", "القصار"),
    ("Al Nuaija", "النعيجة"),
    ("Al Nasraniya", "النصرانية"),
    ("Al Nasr", "النصر"),
    ("Al Nasiriya", "الناصرية"),
    ("Al Najada", "النجادة"),
    ("Al Murra West", "المرة غرب"),
    ("Al Murra East", "المرة شرق"),
    ("Al Murra", "المرة"),
    ("Al Muntazah", "المنتزه"),
    ("Al Mirqab Al Jadeed", "المرقاب الجديد"),
    ("Al Mirqab", "المرقاب"),
    ("Al Messila", "المسيلة"),
    ("Al Mearad", "المعارض"),
    ("Al Mashaf", "المشاف"),
    ("Al Markhiya", "المرخية"),
    ("Al Mansoura", "المنصورة"),
    ("Al Manaseer", "المناصير"),
    ("Al Maamoura", "المعمورة"),
    ("Al Luqta", "اللقطة"),
    ("Al Khuwair", "الخوير"),
    ("Al Khor", "الخور"),
    ("Al Khessa", "الخصة"),
    ("Al Kharrara", "الخراره"),
    ("Al Kharayej", "الخرايج"),
    ("Al Kharaitiyat", "الخريطيات"),
    ("Al Karaana", "الكرعانة"),
    ("Al Jerian", "الجريان"),
    ("Al Jelaiah", "الجليعة"),
    ("Al Jebailat", "الجبيلات"),
    ("Al Jasra", "الجسرة"),
    ("Al Hilal West", "الهلال غرب"),
    ("Al Hilal East", "الهلال شرق"),
    ("Al Ghuwairiya", "الغويرية"),
    ("Al Gharrafa", "الغرافة"),
    ("Al Egla", "العقلة"),
    ("Al Ebb", "العب"),
    ("Al Ebaib", "العبيب"),
    ("Al Duhail South", "جنوب الدحيل"),
    ("Al Duhail North", "الدحيل الشمالية"),
    ("Al Duhail", "الدحيل"),
    ("Al Doha Al Jadeeda", "الدوحة الجديدة"),
    ("Al Dafna", "الدفنة"),
    ("Al Daayen", "الظعاين"),
    ("Al Bidda", "البدع"),
    ("Al Aziziya", "العزيزية"),
    ("Al Asiri", "العسيري"),
    ("Airport Area - HIA", "منطقة المطار - مطار حمد الدولي"),
    ("Ain Khaled", "عين خالد"),
    ("Abu Sidra", "ابو سدرة"),
    ("Abu Samra", "ابو سمرة"),
    ("Abu Hamour", "ابو هامور"),
]
