# Generated by Django 5.2.10 on 2026-01-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
