# Generated by Django 5.2.10 on 2026-01-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_code",
            field=models.CharField(default="GM/PD0051", max_length=100),
        ),
    ]
