# Generated by Django 3.1 on 2026-01-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20260114_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_multi_select',
            field=models.BooleanField(default=False),
        ),
    ]
