# Generated by Django 3.1 on 2026-01-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_variation_is_multi_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='selection_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
