# Generated by Django 5.2.10 on 2026-01-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "productgallery",
                "verbose_name_plural": "product gallery",
            },
        ),
    ]
