# Generated by Django 5.2.10 on 2026-04-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_product_description_ar_product_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
