# Generated by Django 5.2.10 on 2026-04-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_alter_product_product_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Variation Category",
                "verbose_name_plural": "Variation Categories",
            },
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.variationcategory",
            ),
        ),
    ]
