# Generated by Django 5.2.10 on 2026-04-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_variationcategory_alter_variation_variation_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size")], max_length=100
            ),
        ),
        migrations.DeleteModel(
            name="VariationCategory",
        ),
    ]
