# Generated by Django 5.2.10 on 2026-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_replace_age_category_with_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="margin_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="margin_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
