# Generated by Django 5.2.10 on 2026-07-28 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehousing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouses",
                to="warehousing.supplier",
            ),
        ),
    ]
