# Generated by Django 5.2.10 on 2026-09-10 14:22

import django.db.models.deletion
from django.db import migrations, models


def backfill_product_warehouse_stock(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    ProductWarehouseStock = apps.get_model('warehousing', 'ProductWarehouseStock')
    for product in Product.objects.exclude(warehouse_id=None).filter(stock__gt=0):
        ProductWarehouseStock.objects.create(
            product_id=product.id,
            warehouse_id=product.warehouse_id,
            quantity=product.stock,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_product_barcode_image_product_sku_product_upc"),
        ("warehousing", "0004_own_warehouse"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWarehouseStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="store.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_stocks",
                        to="warehousing.warehouse",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "warehouse"),
                        name="unique_product_warehouse_stock",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_product_warehouse_stock, noop),
    ]
