# Generated by Django 5.2.10 on 2026-09-10 15:08

from django.db import migrations, models


def configure_own_warehouse(apps, schema_editor):
    Warehouse = apps.get_model('warehousing', 'Warehouse')
    Warehouse.objects.filter(code='OWN').update(delivery_days=0)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("warehousing", "0005_product_warehouse_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="delivery_days",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Transit days after the order cutoff. Use 0 for same-day delivery before 19:00.",
            ),
        ),
        migrations.RunPython(configure_own_warehouse, noop),
    ]
