# Generated by Django 5.2.10 on 2026-09-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
