# Generated by Django 5.2.10 on 2026-02-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_alter_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="category_name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ar",
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
