# Generated by Django 5.2.10 on 2026-07-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                help_text="Upload banner image (recommended 1600x600)",
                upload_to="banners/",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Show this banner on the site"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="link",
            field=models.URLField(
                blank=True, help_text="Optional link when the banner is clicked"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="subtitle",
            field=models.CharField(
                blank=True, help_text="Optional subtitle or CTA", max_length=220
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional title shown on the banner",
                max_length=120,
            ),
        ),
    ]
