# Generated by Django 5.2.10 on 2026-08-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_category_category_name_ar_category_category_name_en_and_more'),
        ('home', '0003_alter_banner_image_alter_banner_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title shown on the offer banner', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle or short offer text', max_length=220)),
                ('image', models.ImageField(help_text='Upload offer banner image', upload_to='banners/section_offers/')),
                ('link', models.URLField(blank=True, help_text='Optional link when the offer banner is clicked')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner on the homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional: choose a parent category to show this banner after that section. Leave empty for global rotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_offer_banners', to='category.category')),
            ],
            options={
                'verbose_name': 'Section Offer Banner',
                'verbose_name_plural': 'Section Offer Banners',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
