# Generated by Django 5.2.10 on 2026-08-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_sectionofferbanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(upload_to="banners/")),
                ("link_url", models.URLField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
