# Generated by Django 5.2.10 on 2026-09-10 15:35

from django.db import migrations, models


def seed_pinned_apps(apps, schema_editor):
    AdminPinnedApp = apps.get_model('home', 'AdminPinnedApp')
    for app_label, order in (('store', 10), ('warehousing', 20), ('orders', 30)):
        AdminPinnedApp.objects.get_or_create(
            app_label=app_label,
            defaults={'order': order, 'is_pinned': True},
        )


def remove_seeded_pinned_apps(apps, schema_editor):
    AdminPinnedApp = apps.get_model('home', 'AdminPinnedApp')
    AdminPinnedApp.objects.filter(app_label__in=['store', 'warehousing', 'orders']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_promobanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPinnedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        choices=[
                            ("store", "Store"),
                            ("warehousing", "Warehousing"),
                            ("orders", "Orders"),
                            ("Accounts", "Accounts"),
                            ("carts", "Carts"),
                            ("category", "Category"),
                            ("home", "Home"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_pinned", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pinned admin app",
                "verbose_name_plural": "Pinned admin apps",
                "ordering": ["order", "app_label"],
            },
        ),
        migrations.RunPython(seed_pinned_apps, remove_seeded_pinned_apps),
    ]
