# Generated by Django 5.2.10 on 2026-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("PAYPAL", "PayPal")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
