# Generated by Django 5.2.10 on 2026-07-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0001_initial'),
        ('orders', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='warehousing.supplier'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='warehousing.warehouse'),
        ),
    ]
