# Generated by Django 5.2.10 on 2026-07-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_parcel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[],
            options={
                "verbose_name": "Parcel",
                "verbose_name_plural": "Parcels",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="PendingOrder",
            fields=[],
            options={
                "verbose_name": "Pending Order",
                "verbose_name_plural": "Pending Orders",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="PendingReturn",
            fields=[],
            options={
                "verbose_name": "Pending Return",
                "verbose_name_plural": "Pending Returns",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.RemoveField(
            model_name="order",
            name="parcel_id",
        ),
    ]
