# Generated by Django 5.2.10 on 2026-08-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_parcel_pendingorder_pendingreturn_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Packed", "Packed"),
                    ("Ready for Preparing", "Ready for Preparing"),
                    ("Preparing", "Preparing"),
                    ("Ready for Delivery", "Ready for Delivery"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Completed", "Completed"),
                    ("Return Requested", "Return Requested"),
                    ("Returned", "Returned"),
                    ("Refunded", "Refunded"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("return_request_id", models.CharField(editable=False, max_length=40, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Damaged Product", "Damaged Product"),
                            ("Wrong Product Received", "Wrong Product Received"),
                            ("Defective Product", "Defective Product"),
                            ("Quality Issue", "Quality Issue"),
                            ("Size/Variant Issue", "Size/Variant Issue"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Return Requested", "Return Requested"),
                            ("Under Review", "Under Review"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Awaiting Product", "Awaiting Product"),
                            ("Product Received", "Product Received"),
                            ("Inspection Completed", "Inspection Completed"),
                            ("Refund Processing", "Refund Processing"),
                            ("Refund Completed", "Refund Completed"),
                        ],
                        default="Return Requested",
                        max_length=32,
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("manual_refund", "Manual Refund"),
                            ("store_credit", "Store Credit"),
                            ("replacement", "Product Replacement"),
                            ("none", "No Resolution Yet"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("refund_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("refund_completed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("return_shipping_acknowledged", models.BooleanField(default=False)),
                ("policy_terms_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_request",
                        to="orders.order",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Return Request", "verbose_name_plural": "Return Management"},
        ),
        migrations.CreateModel(
            name="ReturnRequestImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="returns/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="orders.returnrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=32)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_timeline",
                        to="orders.returnrequest",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
