# Generated by Django 5.2.10 on 2026-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_status_updated_by_and_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tax",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_charge",
            field=models.FloatField(default=20.0),
        ),
    ]
