# Generated by Django 5.2.10 on 2026-08-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_remove_order_tax_order_delivery_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Collecting", "Collecting"),
                    ("Ready for Preparing", "Ready for Preparing"),
                    ("Preparing", "Preparing"),
                    ("Ready for Delivery", "Ready for Delivery"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New",
                max_length=50,
            ),
        ),
    ]
