# Generated by Django 5.2.10 on 2026-09-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_alter_order_status_default"),
        ("warehousing", "0003_purchase_document_fields_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Parcel",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Same-Day Delivery", "Same-Day Delivery"),
                    ("2-Day Delivery", "2-Day Delivery"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parcel_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcels",
                        to="orders.order",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parcels",
                        to="warehousing.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcel",
                "verbose_name_plural": "Parcels",
            },
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="orders.parcel",
            ),
        ),
    ]
