# Generated by Django 5.2.10 on 2026-09-09 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_parcel_status(apps, schema_editor):
    Parcel = apps.get_model('orders', 'Parcel')
    for parcel in Parcel.objects.select_related('order').all():
        parcel.status = parcel.order.status
        parcel.status_updated_by_id = parcel.order.status_updated_by_id
        parcel.status_updated_at = parcel.order.status_updated_at
        parcel.save(update_fields=['status', 'status_updated_by', 'status_updated_at'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_delete_parcel_order_delivery_type_parcel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Collecting", "Collecting"),
                    ("Ready for Preparing", "Ready for Preparing"),
                    ("Preparing", "Preparing"),
                    ("Ready for Delivery", "Ready for Delivery"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Processing",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="status_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_updated_parcels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_parcel_status, noop),
    ]
