# Generated by Django 5.2.10 on 2026-09-10 15:08

from datetime import time, timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_delivery_dates(apps, schema_editor):
    Parcel = apps.get_model('orders', 'Parcel')
    for parcel in Parcel.objects.select_related('warehouse').all():
        ordered_at = timezone.localtime(parcel.created_at)
        delivery_days = parcel.warehouse.delivery_days if parcel.warehouse else 2
        after_cutoff = ordered_at.time() > time(19, 0)
        parcel.delivery_date = ordered_at.date() + timedelta(days=delivery_days + int(after_cutoff))
        parcel.save(update_fields=['delivery_date'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_parcel_status"),
        ("warehousing", "0006_shipping_delivery_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_delivery_dates, noop),
    ]
